### ISSUE TITLE
bug: nil spilling used in `compute_expression` function

### ISSUE THREAD

**Issue by ivokub** [Consensys/corset#161] opened 2024-05-27 10:57 UTC
Test case:
```rust
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_corset_from_file() {
        let mut c = _corset_from_file("/home/ivo/temp/cur/zkevm.bin").unwrap();
        let t = _compute_trace_from_file(&mut c, "/home/ivo/temp/cur/1_15024091914360580354.lt", true);
        if !t.is_ok() {
            eprintln!("{:?}", t.err());
        }
    }
}
```

Leads to the following stack trace:
```
---- tests::test_corset_from_file stdout ----
thread 'tests::test_corset_from_file' panicked at src/compute.rs:390:44:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
             at /build/rustc-mQ6oHL/rustc-1.75.0+dfsg0ubuntu1~bpo10/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /build/rustc-mQ6oHL/rustc-1.75.0+dfsg0ubuntu1~bpo10/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /build/rustc-mQ6oHL/rustc-1.75.0+dfsg0ubuntu1~bpo10/library/core/src/panicking.rs:127:5
   3: core::option::Option<T>::unwrap
             at /build/rustc-mQ6oHL/rustc-1.75.0+dfsg0ubuntu1~bpo10/library/core/src/option.rs:931:21
   4: corset::compute::compute_expression
             at ./src/compute.rs:390:20
   5: corset::compute::apply_computation
             at ./src/compute.rs:555:22
   6: corset::compute::compute_all::{{closure}}
             at ./src/compute.rs:154:32
   7: core::ops::function::impls::<impl core::ops::function::FnMut<A> for &mut F>::call_mut
             at /build/rustc-mQ6oHL/rustc-1.75.0+dfsg0ubuntu1~bpo10/library/core/src/ops/function.rs:294:13
   8: <core::slice::iter::Iter<T> as core::iter::traits::iterator::Iterator>::find_map
             at /build/rustc-mQ6oHL/rustc-1.75.0+dfsg0ubuntu1~bpo10/library/core/src/slice/iter/macros.rs:319:38
   9: <core::iter::adapters::filter_map::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next
             at /build/rustc-mQ6oHL/rustc-1.75.0+dfsg0ubuntu1~bpo10/library/core/src/iter/adapters/filter_map.rs:62:9
  10: alloc::vec::Vec<T,A>::extend_desugared
             at /build/rustc-mQ6oHL/rustc-1.75.0+dfsg0ubuntu1~bpo10/library/alloc/src/vec/mod.rs:2853:35
  11: <alloc::vec::Vec<T,A> as alloc::vec::spec_extend::SpecExtend<T,I>>::spec_extend
             at /build/rustc-mQ6oHL/rustc-1.75.0+dfsg0ubuntu1~bpo10/library/alloc/src/vec/spec_extend.rs:17:9
  12: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter_nested::SpecFromIterNested<T,I>>::from_iter
             at /build/rustc-mQ6oHL/rustc-1.75.0+dfsg0ubuntu1~bpo10/library/alloc/src/vec/spec_from_iter_nested.rs:43:9
  13: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
             at /build/rustc-mQ6oHL/rustc-1.75.0+dfsg0ubuntu1~bpo10/library/alloc/src/vec/spec_from_iter.rs:33:9
  14: <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter
             at /build/rustc-mQ6oHL/rustc-1.75.0+dfsg0ubuntu1~bpo10/library/alloc/src/vec/mod.rs:2753:9
  15: core::iter::traits::iterator::Iterator::collect
             at /build/rustc-mQ6oHL/rustc-1.75.0+dfsg0ubuntu1~bpo10/library/core/src/iter/traits/iterator.rs:2054:9
  16: corset::compute::compute_all
             at ./src/compute.rs:151:18
  17: corset::compute::prepare
             at ./src/compute.rs:625:5
  18: corset::compute::compute_trace
             at ./src/compute.rs:646:5
  19: corset::_compute_trace_from_file
             at ./src/lib.rs:234:5
  20: corset::tests::test_corset_from_file
             at ./src/lib.rs:531:17
  21: corset::tests::test_corset_from_file::{{closure}}
             at ./src/lib.rs:529:31
  22: core::ops::function::FnOnce::call_once
             at /build/rustc-mQ6oHL/rustc-1.75.0+dfsg0ubuntu1~bpo10/library/core/src/ops/function.rs:250:5
  23: core::ops::function::FnOnce::call_once
             at /build/rustc-mQ6oHL/rustc-1.75.0+dfsg0ubuntu1~bpo10/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Looks like in `compute.rs` on line 390
```rust
let spilling = cs.spilling_of(&module).unwrap();
```
is a getter from pre-computed spilling, but it is yet to be computed. By debugging it seems the module we're asking for is "`<prelude>`".

cc @DavePearce, @powerslider

**Comment by delehef** [comment] 2024-05-27 13:03
All the spillings (especially the `<prelude>` one, which is the root context) should have been serialized in the `.bin` file. Are we 100% sure that this `.bin` file has been generated with a recent version of Corset? What does a `dbg!(&cs.columns.spillings);` show?

**Comment by DavePearce** [comment] 2024-05-27 20:51
Hmmm, is it possible its related to the fix I reverted for spilling optimisations?  I will investigate this shortly.

**Comment by DavePearce** [comment] 2024-05-27 23:10
> What does a `dbg!(&cs.columns.spilling);` show?

@delehef Looks like this:

```
[src/compute.rs:391] &cs.columns.spilling = {
    "mul": 8,
    "mmu": 6,
    "logdata": 1,
    "add": 1,
    "shfreftable": 0,
    "trm": 7,
    "romlex": 0,
    "rlptxrcpt": 7,
    "mxp": 3,
    "blake2fmodexpdata": 0,
    "txndata": 1,
    "euc": 1,
    "instdecoder": 0,
    "rom": 1,
    "shf": 15,
    "wcp": 15,
    "ecdata": 1,
    "blockhash": 1,
    "bin": 15,
    "blockdata": 1,
    "stp": 1,
    "rlpaddr": 7,
    "rlptxn": 7,
    "loginfo": 1,
    "binreftable": 0,
    "mmio": 0,
    "mod": 7,
    "ext": 7,
}
```

**Comment by DavePearce** [comment] 2024-05-27 23:18
So, for this test case:

```
(defcolumns (X :nibble) (Y :byte) (Z :i128))
(defconstraint test () (vanishes! (if-zero X Y Z)))
```

We get this debug output:

```
[src/compute.rs:391] &cs.columns.spilling = {
    "<prelude>": 0,
}
```

That looks OK.

**Comment by DavePearce** [comment] 2024-05-27 23:33
Wait, is this related to #151 ???

**Comment by DavePearce** [comment] 2024-05-27 23:56
Ok, maybe we have a clue here:

```
(deflookup test (m2.A) ((shift (~ m1.B) -2)))

(module m1)
(defcolumns B)

(module m2)
(defcolumns A)
(defconstraint test () (vanishes! (- 1 A)))
```
This leads to a `bin` file which has no spilling information for the `prelude`.  However, it also doesn't crash either

**Comment by DavePearce** [comment] 2024-05-28 02:07
Ok, finally.  It took a while to get this.  Here is the minimal test case to reproduce:

```
(deflookup test (m1.A) (0))

(module m1)
(defcolumns A)
(defconstraint test () (vanishes! (- 1 A)))
```

With a trace like this:

```
{ "m1": {"A": [0]}}
```

Then, a command-line like this:

```
$ corset compute --trace test.trace --out test.out test.lisp
thread 'main' panicked at src/compute.rs:391:44:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

We can also compile it to the `bin` file and see the same effect and/or use an `lt` file directly.  In the `bin` file, for example, you see this:

```
spilling:{"m1":0}
```

Indicating that precomputed spilling information for  `<prelude>` is missing.

**Comment by DavePearce** [comment] 2024-05-28 02:22
Some observations:

1. Spilling information is determined for every module which creates a column.

**Comment by DavePearce** [comment] 2024-05-28 03:30
Removing the `spilling` field altogether is hard to do at this stage.  Incrementally updating the `spilling` information makes more sense, but we'd want to first encapsulate `ConstraintSet` properly --- which would be painful.

**Comment by DavePearce** [comment] 2024-05-28 03:50
Ok, the infinite loop appears to be a separate issue.  Specifically, on `master` the following test:

```
(module m1)
(defcolumns X)
(deflookup test (m2.A) (0))

(module m2)
(defcolumns A)
(defconstraint test () (vanishes! (- 1 A)))
```

With a trace like the following:

```
{ "m1": {"X": [0]}, "m2": {"A": [0]}}
```

Enters a similar infinite loop.  I crafted this example carefully to avoid triggering the bug being investigated here.  As such, this is a separate problem.  Clearly it must have something to do with the constant expression `0`.

**Comment by DavePearce** [comment] 2024-05-28 03:59
And here's why.  Its writing this file endlessly:

```
{"columns":{
"m1.X":{
"values":["0x00","0x00"],
"padding_strategy": {"action": "prepend", "value": "0"}
}
,"m1.C/#EXPAND[0]":{
"values":["0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00"
,"0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","
0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x
00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00
","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00",
"0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0
x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x0
0","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00"
,"0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","
0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x
00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00
","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00",
"0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0
x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x0
0","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00"
,"0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","
0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x00","0x
00","0x00","0x00" ...
```

**Comment by DavePearce** [comment] 2024-05-28 04:27
Ok, I've cut a preliminary PR [here](https://github.com/Consensys/corset/pull/164).  But, the test ivo gave above is not terminating for reasons unknown.  Running it directly using `corset compute` from the command line seems fine though.

**Comment by DavePearce** [comment] 2024-05-28 04:53
Ok, narrowed it down to `ValueBackingIter` in `column.rs`:

```rust
impl<'a> Iterator for ValueBackingIter<'a> {
    type Item = Value;

    fn next(&mut self) -> Option<Self::Item> {
        match self.value {
            ValueBacking::Vector { v, .. } => { ... }
            ValueBacking::Expression { .. } => { ... }                
            ValueBacking::Function { f, .. } => {
                self.i += 1;
                f(self.i - 1, self.columns)
            }
        }
    }
}
```
Specifically, case for `ValueBacking::Function` is non-terminating.

**Comment by DavePearce** [comment] 2024-05-28 23:58
Have been thinking about this issue overnight and need to revisit the solution in light of #166.  The actual problem here can be more succinctly expressed as follows:

- For a lookup involving a constant expression e.g. `(deflookup (m2.A m2.B) (0 m1.Y))` ...
- ... `corset` creates a computed column for the constant expression ...
- ... and places it into the _enclosing module_.

This is important, and it means the proposed solutions above are headed in the wrong direction.  In fact, `corset` has some logic already to deal with this kind of situation.  For example, consider this:

```
(deflookup test (m2.A m2.B) ((* 2 m1.X) m1.Y))
```

In this case, `corset` correctly places the computed column for `(* 2 m1.X)` into the `m1` module.  This logic needs to be extended in two ways:

1. In the case that `corset` cannot determine module where the computed column should go, _then an error should be reported_.  I guess that it currently defaults to the `<prelude>` which has caused confusion here.
2. For every lookup, `corset` should identify the enclosing module for both the target (resp. source) columns.  If there is ambiguity, an error should be reported.  Then any computed columns go into the relevant module regardless.

**Comment by DavePearce** [comment] 2024-05-29 00:21
I think the existing logic is implemented via things like this (from `transformers::do_expand_expr()`):

```
let module = cols
         .module_for(e.dependencies())
         .unwrap_or(module.to_owned())
```

That makes sense.  But, what we can see is that there is insufficient information at this point to determine the correct module.  Likewise, `unwrap_or(module.to_owned())` is probably a bad idea.

**Comment by delehef** [comment] 2024-05-29 00:50
To add to your remarks, it is true that the infinite iterator over `ValueBacking::Function` is extremely dangerous, and should be reworked is possible.

However, to give a bit of context on it: the idea behind the creation of this is that typically, be it for export in whatever format, for checking, etc., the iteration will be done over `cs.iter_len(<SOME_MODULE>)`, and thus will never be the iterator expected to end the loop. Indeed, the `ValueBacking::Function` may typically be used for constant (e.g. for lookups) or cyclic (e.g. for range constraints) functions, that have no reason to exist outside of a bounded module and are just expected to spit as many elements as required by their module.

Here, with `(deflookup test (m2.A) (0))`, you hit this very interesting edge case of “lookup-ing” over a module (`<prelude>`, as there is only the `0` constant on the right hand side of the lookup) that contains... nothing.

Given that I can not see any use case where looking up free-standing (i.e. column-less) expressions would make sense, I think the best (or less worse...) solutions would be to increase the severity of the `deflookup` validator to refuse any lookup where the left-hand side and the right-hand side modules would be well defined through the use of `Expression::leaves` to determine the raw columns used in both.

**Comment by DavePearce** [comment] 2024-05-29 01:39
> would be to increase the severity of the deflookup validator to refuse any lookup

I think any situation where the module in which the source (or target) columns cannot be determined ... should be rejected.  I'm wondering whether there are any valid use cases which would break because of this.

**Comment by DavePearce** [comment] 2024-05-29 01:40
> and thus will never be the iterator expected to end the loop

Yeah, I realised this eventually.  So my attempts to change the termination conditions were misguided.  Instead, its the constraints themselves which are the problem!!

**Comment by DavePearce** [comment] 2024-05-29 01:45
> Likewise, unwrap_or(module.to_owned()) is probably a bad idea.

So removing this now causes the two strange situations, specifically these, to result in a panic:

```
(deflookup test (m1.A) (0))
```
and
```
(deflookup test (m3.A) ((* m1.X m2.Y)))
```
Probably we need a better error message.  Furthermore, the `zkevm.bin` still compiles ... meaning it doesn't itself violate these constraints.  However, we do know that the expanded column will.

**Comment by delehef** [comment] 2024-05-29 02:03
> I think any situation where the module in which the source (or target) columns cannot be determined ... should be rejected. I'm wondering whether there are any valid use cases which would break because of this.

Agreed on that. I guess that on the degenerated case one could fallback on the other hand module length, but safe for the theoretical satisfaction, I can not imagine any real use case where that would be useful.

> Probably we need a better error message. 

Agreed as well, expanded my meaning in #166.

**Comment by DavePearce** [comment] 2024-05-29 03:33
Ok, we finally have a fix for this that I am at least somewhat happy with.  The original test from @ivokub now passes, and also it passes when running `corset check` from the command-line.  The various strange test cases I've come up with are now rejected with an error such as the following:

```
Error: ambiguous source module for lookup test
```

The error message could be improved, and I leave #166 open to address that.

**Closed** 2024-05-29 03:34 UTC
Labels: bug
